require('../database/connect')
const express= require("express")
const app = express()
app.use(express.json())
const path = require("path")
const staticDir = path.join(__dirname, "../images")
app.use(express.static(staticDir))
app.use(express.urlencoded({extended:true}))
const userRoutes=require("../routes/room.routes")
app.use("/room",userRoutes)
const hotelRoutes=require("../routes/hotel.routes")
app.use("/hotel",hotelRoutes)
module.exports = app
